title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-02
owner: ucsb-cs156-f24
repo_name: team02-f24-02
pull_requests: [{"author":{"id":"U_kgDOBuPHZA","is_bot":false,"login":"leozhu0","name":""},"headRefName":"leozhu0-UCSBDiningCommonsMenuItem-backend","number":71,"title":"Created ucsbDiningCommonsMenuItemFixtures.js","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/71"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReviews-CreatePage","number":70,"title":"Vp Menu Item Reviews Create Page","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/70"},{"author":{"id":"U_kgDOB3Cn0w","is_bot":false,"login":"EduinoMEH","name":"Edwin E. Medrano Villela"},"headRefName":"eduinomeh-UCSBOrganizations-Components","number":69,"title":"Form Component for UCSBOrganization Finished, All Mutations Met","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/69"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReviews-Placeholders","number":67,"title":"VP MenuItemReviews Placeholdrs","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/67"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReviews-TableComponent","number":66,"title":"VP MenuItemReviews Tables","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/66"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReviews-FormComponent","number":65,"title":"VP menu item reviews form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/65"},{"author":{"id":"U_kgDOB3Cn0w","is_bot":false,"login":"EduinoMEH","name":"Edwin E. Medrano Villela"},"headRefName":"eduinomeh-UCSBOrganizations-Fixtures","number":61,"title":"Finished UCSBOrganizations Fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/61"}]
