title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-02
owner: ucsb-cs156-f24
repo_name: team02-f24-02
pull_requests: [{"author":{"id":"MDQ6VXNlcjI5Njc5MDYz","is_bot":false,"login":"billybobjoe123","name":""},"headRefName":"articlepages","number":101,"title":"Table + tests, Create page+tests, Edit page + tests, index page + tests, placeholders for app.js and appnavbar.js","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/101"},{"author":{"id":"MDQ6VXNlcjY1ODc1MjE3","is_bot":false,"login":"rushil-x-gupta","name":""},"headRefName":"rg-HelpRequest-placeholders","number":100,"title":"rg - added placeholders","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/100"},{"author":{"id":"U_kgDOB2W7yQ","is_bot":false,"login":"berdly","name":"Jakob Pinedo"},"headRefName":"berdly-rec-request-edit-page","number":96,"title":"Add Edit page for Recommendation Request","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/96"},{"author":{"id":"U_kgDOB2W7yQ","is_bot":false,"login":"berdly","name":"Jakob Pinedo"},"headRefName":"berdly-rec-request-index-page","number":95,"title":"Added Index page for RecommendationRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/95"},{"author":{"id":"U_kgDOB2W7yQ","is_bot":false,"login":"berdly","name":"Jakob Pinedo"},"headRefName":"berdly-rec-request-create-page","number":94,"title":"Added Create Page for Recommendation Request","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/94"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReviews-Tests","number":92,"title":"Vp menu item reviews tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/92"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReviews-EditPage","number":80,"title":"Vp menu item reviews edit page","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/80"}]
