title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-02
owner: ucsb-cs156-f24
repo_name: team02-f24-02
pull_requests: [{"author":{"id":"U_kgDOB3Cn0w","is_bot":false,"login":"EduinoMEH","name":"Edwin E. Medrano Villela"},"headRefName":"eduinomeh-UCSBOrganizations-E2E","number":123,"title":"Finished 2E2 for UCSBOrganizations, 1 Test Developed","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/123"},{"author":{"id":"MDQ6VXNlcjI5Njc5MDYz","is_bot":false,"login":"billybobjoe123","name":""},"headRefName":"team03-billybobjoe123","number":122,"title":"Team03 billybobjoe123","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/122"},{"author":{"id":"U_kgDOB3Cn0w","is_bot":false,"login":"EduinoMEH","name":"Edwin E. Medrano Villela"},"headRefName":"eduinomeh-UCSBOrganizations-IT","number":121,"title":"Finished IT for UCSBOrganizations - 2 IT Tests Completed","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/121"}]
