title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-02
owner: ucsb-cs156-f24
repo_name: team02-f24-02
pull_requests: [{"author":{"id":"MDQ6VXNlcjY1ODc1MjE3","is_bot":false,"login":"rushil-x-gupta","name":""},"headRefName":"rg-HelpRequest-create","number":104,"title":"rg - finished create page","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/104"},{"author":{"id":"U_kgDOB2W7yQ","is_bot":false,"login":"berdly","name":"Jakob Pinedo"},"headRefName":"fix-routing","number":103,"title":"Hot Fix for Routing Issue in MenuItemReview","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/103"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReviews-Tests","number":92,"title":"Vp menu item reviews tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/92"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReviews-EditPage","number":80,"title":"Vp menu item reviews edit page","url":"https://github.com/ucsb-cs156-f24/team02-f24-02/pull/80"}]
